import timeit
from unitflex import config
config.DEBUG = False
def convertOperation():
    import unitflex as uf
    uf.length.convert(1.2345, "lightyear", "femtometer", mode="engineering", delim="default")
    uf.mass.convert(1.2345, "earthmass", "dalton", mode="engineering", delim="default")
    uf.time.convert(15.3465, "century", "day", delim="default")
    uf.data.convert(1.231, "GiB", "TiB", mode="engineering")
    uf.speed.convert(1.0, "c", "mach", mode="eng", de=True, prec=12, fmt="tag")
    uf.pressure.convert(1000000, "dyne/cm2", "atm", mode="engineering", delim="default")
    uf.volume.convert(5.678, "liter", "milliliter", mode="engineering", delim=True)
    uf.temperature.convert(300, "kelvin", "celsius", mode="engineering")
    uf.length.convert(9.8765, "astronomicalunit", "centimeter", mode="engineering", delim="default")
    uf.mass.convert(3.1415, "kilogram", "ton", mode="engineering", delim="default")
    uf.time.convert(5000, "minute", "second", delim="default")
    uf.data.convert(1.25, "MiB", "KiB", mode="engineering", delim=True)
    uf.speed.convert(2.0, "mach", "m/s", mode="engineering", prec=10, fmt="verbose")
    uf.pressure.convert(100, "barye", "pa", mode="engineering", delim="default")
    uf.volume.convert(123456, "gallon", "m3", mode="engineering", delim=False)
    uf.temperature.convert(298.15, "kelvin", "fahrenheit", mode="engineering", delim="default")
    uf.length.convert(1.0, "mile", "foot", mode="engineering", delim="default")
    uf.mass.convert(0.000234, "earthmass", "gram", mode="engineering", delim="default")
    uf.time.convert(10, "year", "second", delim="default")
    uf.data.convert(5.67, "KiB", "GiB", mode="engineering", delim=True)
    uf.speed.convert(1.5, "m/s", "km/h", mode="eng", prec=8, fmt="tag")
    uf.pressure.convert(2.5, "atm", "mmHg", mode="engineering", delim="default")
    uf.volume.convert(0.000123, "m3", "liter", mode="engineering", delim=True)
    uf.temperature.convert(0, "celsius", "kelvin", mode="engineering", delim="default")
    uf.length.convert(1000, "millimeter", "kilometer", mode="engineering", delim="default")
    uf.mass.convert(1.0, "ton", "kilogram", mode="engineering", delim="default")
    uf.time.convert(0.5, "hour", "minute", delim="default")
    uf.data.convert(1024, "MiB", "GiB", mode="engineering", delim=True)
    uf.speed.convert(3.6, "km/h", "m/s", mode="eng", de=True, prec=15, fmt="verbose")
    uf.pressure.convert(1.0, "atm", "dyne/cm2", mode="engineering", delim="default")
    uf.volume.convert(2.5, "liter", "gallon", mode="engineering", delim=False)
    uf.temperature.convert(0.0, "celsius", "fahrenheit", mode="engineering", delim="default")


executionTime = timeit.timeit(convertOperation, number=10)
executionTimeInMs = executionTime * 1000
print(f"[Convert] Execution Time: {executionTime:.6f} seconds or {executionTimeInMs:.3f} ms")

def flexOperation():
    import unitflex as uf
    uf.time.flex(15.3465, "century", flexRange=("hour", "second"), delim=False)
    uf.time.flex(1024.6789, "decade", flexRange=("minute", "second"), delim=True)
    uf.time.flex(0.1234, "year", flexRange=("month", "second"), delim=False)
    uf.time.flex(3.5678, "month", flexRange=("day", "second"), delim=True)
    uf.time.flex(7896.54321, "week", flexRange=("hour", "second"), delim=False)
    uf.time.flex(10.9876, "day", flexRange=("minute", "second"), delim=True)
    uf.time.flex(1.234567, "hour", flexRange=("minute", "second"), delim=False)
    uf.time.flex(0.0009, "minute", flexRange=("second", "second"), delim=True)
    uf.time.flex(345.6789, "second", flexRange=("minute", "second"), delim=False)
    uf.time.flex(5000.2468, "century", flexRange=("year", "second"), delim=True)
    uf.time.flex(0.000234, "decade", flexRange=("month", "second"), delim=False)
    uf.time.flex(789.123, "year", flexRange=("month", "minute"), delim=True)
    uf.time.flex(876.4321, "month", flexRange=("week", "second"), delim=False)
    uf.time.flex(3.5642, "week", flexRange=("day", "minute"), delim=True)
    uf.time.flex(2345.6789, "day", flexRange=("hour", "minute"), delim=False)
    uf.time.flex(12.3456, "hour", flexRange=("minute", "second"), delim=True)
    uf.time.flex(1.9876, "minute", flexRange=("second", "second"), delim=False)
    uf.time.flex(543.2109, "second", flexRange=("minute", "minute"), delim=True)
    uf.time.flex(9.8765, "century", flexRange=("year", "hour"), delim=False)
    uf.time.flex(67.8901, "decade", flexRange=("month", "week"), delim=True)
    uf.time.flex(0.5678, "year", flexRange=("week", "second"), delim=False)
    uf.time.flex(123.4567, "month", flexRange=("day", "second"), delim=True)
    uf.time.flex(56.7890, "week", flexRange=("hour", "minute"), delim=False)
    uf.time.flex(432.1234, "day", flexRange=("hour", "minute"), delim=True)
    uf.time.flex(0.123456, "hour", flexRange=("minute", "second"), delim=False)
    uf.time.flex(3456.7890, "minute", flexRange=("second", "second"), delim=True)
    uf.time.flex(0.00001234, "second", flexRange=("minute", "minute"), delim=False)
    uf.time.flex(6789.1234, "century", flexRange=("decade", "hour"), delim=True)
    uf.time.flex(987.6543, "decade", flexRange=("year", "second"), delim=False)
    uf.time.flex(234.5678, "year", flexRange=("month", "minute"), delim=True)

executionTime = timeit.timeit(flexOperation, number=10)
executionTimeInMs = executionTime * 1000
print(f"[Flex] Execution Time: {executionTime:.6f} seconds or {executionTimeInMs:.3f} ms")